# Fase 2: Preprocesamiento y limpieza de datos

In [1]:
#librerias
import pandas as pd
import numpy as np

# 1. Identificacion de caracteristicas en Trafico normal

In [2]:
#importar db normal, DoS y Probe
df_normal = pd.read_csv('../../datos_SDN/argDatos/Normal.csv', low_memory=False)
df_dos = pd.read_csv('../../datos_SDN/argDatos/Dos.csv', low_memory=False)
df_probe = pd.read_csv('../../datos_SDN/argDatos/Probe.csv', low_memory=False)

In [9]:
"""numero identificador de argus = BAJA"""
df_normal['SrcId'].unique()

array(['0.0.0.0'], dtype=object)

In [8]:
"""numero de secuencia del registro de flujo = BAJA 
(varia en caracteristicas de hardware y el flujo es independiente de la hora de inicio)"""
df_normal.Rank.unique()

array([       nan, 1.0000e+00, 2.0000e+00, ..., 2.4392e+04, 2.4393e+04,
       2.4394e+04])

In [10]:
"""registro de hora de inicio del flujo = BAJA 
(varia en caracteristicas de hardware y el flujo es independiente para finalizar)"""
df_normal.StartTime.unique()

array(['20:58:47.678596', '09:25:49.449442', '09:25:49.639147', ...,
       '14:24:16.244081', '14:24:17.269716', '21:31:06.419509'],
      dtype=object)

In [11]:
""" contador de registros de flujos agregados = BAJA"""
df_normal.Trans.unique()

array([nan,  1.])

In [12]:
""" banderas o indicadores de control en el estado de la transaccion del flujo = MEDIA
(indica el proposito del que tiene el paquete o segmento)"""
df_normal.Flgs.unique()

array(['          ', ' M        ', ' e        ', ' M g      ',
       ' M r      ', ' M dS     ', ' e g      ', ' e     A  ',
       ' eU       ', ' M d      ', ' e s      ', ' M s      ',
       ' e d      ', ' M  S     ', ' M i      ', ' M  D     ',
       ' M sD     ', ' M &      ', ' e *      ', ' M *      ',
       ' e dD     '], dtype=object)

In [13]:
""" numero de sequencia de argus = BAJA
(es una caracteristica propia del extractor de flujo)
"""
df_normal.Seq.unique()

array([    0,     1,     2, ..., 18682, 18683, 18684], dtype=int64)

In [14]:
""" duracion del flujo en segundos = ALTA
"""
df_normal.Dur.unique()

array([6.4700000e-04, 1.1450987e+01, 1.2774145e+01, ..., 2.0255120e+00,
       1.3001590e+00, 1.0164340e+00])

In [15]:
"""tiempo total de ejecución del flujo activo = ALTA 
(posible atributo redundante al Dur)
"""
df_normal.RunTime.unique()

array([      nan, 11.450987, 12.774145, ...,  7.920346,  2.025512,
        1.300159])

In [16]:
""" tiempo inactivo del ultimo flujo o paquete = MEDIO
(valor estadistivo de referencia del ultima actividad del flujo para recomenzar el siguiente flujo)
"""
df_normal.IdleTime.unique()

array([           nan, 1.67271117e+09, 1.67271334e+09, 1.67271142e+09,
       1.67271168e+09, 1.67271219e+09, 1.67271232e+09, 1.67271245e+09,
       1.67271270e+09, 1.67271283e+09, 1.67271296e+09, 1.67271309e+09])

In [17]:
""" promedio de duracion de cada flujo registrado = ALTA
(valor estadistico para conocer la duracion promedia de los diferentes flujos en diferentes traficos)
(posible atributo redundante al Dur)
"""
df_normal.Mean.unique()

array([      nan, 11.450987, 12.774145, ...,  7.920346,  2.025512,
        1.300159])

In [19]:
""" desviacion estandar del tiempo de duracion del flujo registrado = ALTA
"""
df_normal.StdDev.unique()

array([nan,  0.])

In [18]:
""" Suma total de la duracion del flujo = ALTA
(indica el tiempo total que dura la transaccion)
(posible atributo redundante al Dur)
"""
df_normal.Sum.unique()

array([      nan, 11.450987, 12.774145, ...,  7.920346,  2.025512,
        1.300159])

In [21]:
""" Valor minimo de la duracion del flujo = ALTA
(posible atributo redundante al Dur)
"""
df_normal.Min.unique()

array([      nan, 11.450987, 12.774145, ...,  7.920346,  2.025512,
        1.300159])

In [20]:
""" valor maximo de la duracion del flujo = ALTA
(posible atributo redundante al Dur)
"""
df_normal.Max.unique()

array([      nan, 11.450987, 12.774145, ...,  7.920346,  2.025512,
        1.300159])

In [22]:
"""direccion MAC de origen = BAJA
(el flujo debe identificarse independientemente de los identificadores de hosts)"""
df_normal.SrcMac.unique()

array([nan, '00:00:00:00:00:03', '00:0c:29:2d:74:6b', '00:0c:29:92:12:ba',
       '00:50:56:c0:00:01', '02:eb:9f:67:c9:42', '00:50:56:f2:90:f8',
       '00:0c:29:92:12:d8', '00:50:56:c0:00:08', '3a:1f:c0:c6:05:00',
       '00:0c:29:2d:74:75'], dtype=object)

In [23]:
"""direccion MAC de destino = BAJA
(el flujo debe identificarse independientemente de los identificadores de hosts)"""
df_normal.DstMac.unique()

array([nan, '00:0c:29:92:12:d8', '00:50:56:f2:90:f8', '00:0c:29:92:12:ba',
       '00:0c:29:2d:74:6b', 'Broadcast', '01:00:5e:7f:ff:fa',
       '01:00:5e:00:00:fb', '33:33:00:00:00:fb', '33:33:00:01:00:03',
       '01:00:5e:00:00:fc', '33:33:00:00:00:02', '33:33:00:00:00:16',
       '01:00:5e:00:00:16', '01:80:c2:00:00:0e', '00:00:00:00:00:03',
       '33:33:00:00:00:01', '00:50:56:c0:00:01'], dtype=object)

In [24]:
""" atributo desconocido y valores FALTANTES"""
df_normal.SrcOui.unique()

array([nan])

In [25]:
""" atributo desconocido y valores FALTANTES"""
df_normal.DstOui.unique()

array([nan])

In [26]:
"""direccion IP origen  = BAJA
(el flujo debe identificarse independientemente de los identificadores de hosts)"""
df_normal.SrcAddr.unique()

array(['0', '192.168.20.133', '192.168.8.128', '192.168.8.129',
       '192.168.8.1', 'fe80::a9c8:a7bc:187d:eb55',
       'fe80::20c:29ff:fe2d:746b', '01:80:c2:00:00:0e',
       '02:eb:9f:67:c9:42', '192.168.20.2', '192.168.20.129',
       '192.168.20.1', 'fe80::381f:c0ff:fec6:500', 'fe80::200:ff:fe00:3',
       '169.254.5.255', 'fe80::20c:29ff:fe92:12ba'], dtype=object)

In [27]:
"""direccion IP destino  = BAJA
(el flujo debe identificarse independientemente de los identificadores de hosts)"""
df_normal.DstAddr.unique()

array(['0', '173.194.129.231', '74.125.193.94', ..., '46.137.81.30',
       '62.212.64.229', '52.26.57.93'], dtype=object)

In [28]:
"""protocolo que usa el flujo para la transaccion = ALTA
protocolos de capa 2, 3 y 4
"""
df_normal.Proto.unique()

array(['man', 'tcp', 'udp', 'ipv6-icmp', 'igmp', 'lldp', 'unknown', 'arp',
       'icmp'], dtype=object)

In [29]:
""" puerto de origen == BAJA 
uso de puertos dinamicos
"""
df_normal.Sport.unique()

array(['0', '51780', '36764', ..., '53368', '61636', '51640'],
      dtype=object)

In [31]:
""" puerto de destino == ALTA 
uso de puertos conocidos o registrados
"""
df_normal.Dport.unique()

array(['0', 'https', 'http', ..., '52815', '38627', '38338'], dtype=object)

In [32]:
""" valor del byte de la cabecera para indicar el tipo de servicio que consume el origen == BAJA"""
df_normal.sTos.unique()

array([ nan,   0., 192., 195., 112., 244., 124.,  45., 206.,  27., 252.,
        66.,  24., 247., 169., 128., 233., 106.,  98., 123.,   1.,  28.,
       102., 234., 138.,  65.,  58.,  71.,   9., 135., 253., 111.,  18.,
       132., 237.,  81.,  26., 182.,  64., 251., 228., 167.,  59., 164.,
        62., 140., 185.,  63.,  67., 103., 146.,  55., 154., 202.,  78.,
       100., 231.,  74., 229., 238., 136., 139.,  83.,  16., 197., 221.,
       129.,  31., 222., 210., 155., 125.,  22.,  54.,  11., 218.,  86.,
        99., 186., 172., 212., 211., 104., 120.,  80., 175., 157.,  73.,
        88., 255., 126.,  19.,  97.,  39.,  50., 163.,  25., 143.,   3.,
       194.,  60., 170., 134.,  17., 160., 205.])

In [144]:
""" valor del byte de la cabecera para indicar el tipo de servicio que brinda el destino == BAJA"""
df_normal.dTos.unique()

array([ nan,   0., 192.,  16.,   8.])

In [34]:
""" byte del estado del host de origen === ?
"""
df_normal.sDSb.unique()

array([nan, 'cs0', 'cs6', 'af32', '61', '31', '11', '51', ' 6', '63',
       'cs2', '42', 'cs4', '58', 'af31', 'cs3', 'af33', ' 7', '25',
       'af41', 'af13', '17', ' 2', '33', '27', ' 4', '59', 'af22', '45',
       '62', '57', '41', '15', '35', 'ef', 'af42', '13', 'af43', '50',
       '19', 'af21', '49', '55', '52', ' 5', '54', '21', '43', '53', '39',
       'af23', ' 9', 'af12', 'cs5'], dtype=object)

In [36]:
""" byte del estado del host de destino === ?
"""
df_normal.dDSb.unique()

array([nan, 'cs0', 'cs6', ' 4', ' 2'], dtype=object)

In [37]:
"""codigo de localizacion de la direccion IP de origen  == BAJA """
df_normal.sCo.unique()

array([nan])

In [38]:
"""codigo de localizacion de la direccion IP de destino  == BAJA """
df_normal.dCo.unique()

array([nan])

In [39]:
""" tiempo de vida del paquete de origen a destino = MEDIA
"""
df_normal.sTtl.unique()

array([ nan,  64., 128.,   1., 255.,   4.,  63.])

In [40]:
""" tiempo de vida del paquete de destino a origen = MEDIA
"""
df_normal.dTtl.unique()

array([ nan, 128.,  64.,  63.])

In [45]:
"""numero de saltos de nodos del host origen =BAJA
"""
df_normal.sHops.unique()

array([nan,  0.,  1.])

In [42]:
"""numero de saltos de nodos del host destino =BAJA
"""
df_normal.dHops.unique()

array([nan,  0.,  1.])

In [43]:
""" identificador de cabecera para direccion IP del host origen =BAJA
"""
df_normal.sIpId.unique()

array([nan, '0x70fe', '0x0000', ..., '0x121a', '0x3586', '0x741a'],
      dtype=object)

In [44]:
""" identificador de cabecera para direccion IP del host destino =BAJA"""
df_normal.dIpId.unique()

array([nan, '0xae22', '0xbf22', ..., '0x4a99', '0x0123', '0x411f'],
      dtype=object)

In [46]:
""" identificador de protocolo MPLS de origen = BAJA """
df_normal.sMpls.unique()

array([nan])

In [47]:
""" identificador de protocolo MPLS de destino = BAJA """
df_normal.dMpls.unique()

array([nan])

In [48]:
""" atributo desconocido"""
df_normal.AutoId.unique()

array([0], dtype=int64)

In [49]:
""" nro de AS de origen  = BAJA"""
df_normal.sAS.unique()

array([nan])

In [50]:
""" nro de AS de destino  = BAJA"""
df_normal.dAS.unique()

array([nan])

In [51]:
""" nro de AS de intermedio del flujo  = BAJA"""
df_normal.iAS.unique()

array([nan])

In [52]:
"""valor del estado del flujo por argus ==MEDIA 
(indica si el flujo fue de inicio,o envia un estado, cierre o error del establecimiento de la comunicacion"""
df_normal.Cause.unique()

array(['Start', 'Status', 'Stop'], dtype=object)

In [53]:
""" numero total de pulsaciones por caracter == BAJA"""
df_normal.NStrok.unique()

array([nan])

In [54]:
""" numero total de pulsaciones por caracter del equipo origen == BAJA"""
df_normal.sNStrok.unique()

array([nan])

In [55]:
""" numero total de pulsaciones por caracter del equipo destino == BAJA"""
df_normal.dNStrok.unique()

array([nan])

In [56]:
""" Nro total de paquetes en el flujo actual == ALTA"""
df_normal.TotPkts.unique()

array([   0,  786,    8, ..., 1714, 3011, 1400], dtype=int64)

In [57]:
""" Nro total de paquetes en el flujo del host Origen == ALTA"""
df_normal.SrcPkts.unique()

array([    0,   194,     4,     3,     2,   203,     1,     8,   236,
           6,   245,     5,    80,   172,    14,    66,    11,   225,
          10,     9,   144,    13,   141,    16,   143,   157,   267,
          96,   190,   121,     7,    77,   177,    74,   193,    40,
          39,    12,   138,    31,   161,   103,    15,    17,    22,
         341,   571,   243,    41,    28,    24,   151,    47,   429,
          46,    99,    25,    57,   624,   232,    93,    18,    53,
         134,    36,   123,   105,   130,    45,    97,   116,    26,
         290,    20,   181,    21,    88,   175,   162,   120,   142,
         118,   286,   147,   106,   201,   251,   282,   140,   214,
         231,    54,    92,    23,   292,    50,    29,   386,   403,
         168,   388,    19,   188,   365,   154,   153,   608,   689,
         695,   725,   651,   441,    33,  1116,    34,   199,  1233,
        1931,   857,   931,   659,   396,    52,    49,   675,   156,
         862,   706,

In [58]:
""" Nro total de paquetes en el flujo del host destino == ALTA"""
df_normal.DstPkts.unique()

array([   0,  592,    4, ..., 2720, 2560, 1389], dtype=int64)

In [59]:
""" Total de bytes en todo el flujo actual = ALTA  """
df_normal.TotBytes.unique()

array([       0,  1983312,      456, ...,    26758,   252032, 10999284],
      dtype=int64)

In [61]:
""" cantidad de bytes emitidos de origen a destino = ALTA  """
df_normal.SrcBytes.unique()

array([     0,  12954,    216, ..., 388847, 236653, 130600], dtype=int64)

In [62]:
""" cantidad de bytes emitidos de destino a origen = ALTA  """
df_normal.DstBytes.unique()

array([      0, 1970358,     240, ...,  213449,  121432,     946],
      dtype=int64)

In [63]:
"""total de bytes de la aplicacion usada en el flujo = MEDIA"""
df_normal.TotAppByte.unique()

array([       0,  1940850,       77, ...,   357690,   198044, 10999284],
      dtype=int64)

In [64]:
"""total de bytes de la aplicacion origen a la aplicacion destino (cliente-servidor) = MEDIA"""
df_normal.SAppBytes.unique()

array([     0,   2478,     77, ..., 281795, 186163, 101296], dtype=int64)

In [65]:
"""total de bytes de la aplicacion destino a la aplicacion origen (servidor-cliente) = MEDIA"""
df_normal.DAppBytes.unique()

array([      0, 1938372,      46, ...,  265713,  171527,   96748],
      dtype=int64)

In [67]:
"""porcentaje de interaccion entre hosts origen y destino = BAJA"""
df_normal.PCRatio.unique()

array([      nan, -0.997446, -0.      , ...,  0.040918,  0.022965,
       -0.793991])

In [68]:
""" Nro de bits por segundo en el flujo = BAJA"""
df_normal.Load.unique()

array([0.00000000e+00, 1.38322962e+06, 2.14182632e+02, ...,
       2.53942453e+05, 1.45371094e+03, 6.53299463e+03])

In [69]:
""" Nro de bits por segundo emitidos por el host origen == BAJA"""
df_normal.SrcLoad.unique()

array([0.00000000e+00, 9.00487598e+03, 1.01454933e+02, ...,
       1.31616469e+05, 1.45371094e+03, 5.09476172e+03])

In [70]:
""" Nro de bits por segundo emitidos por el host destino == BAJA"""
df_normal.DstLoad.unique()

array([0.00000000e+00, 1.37442412e+06, 1.12740479e+02, ...,
       1.28260117e+04, 1.23014289e+05, 1.44045105e+03])

In [71]:
""" total de paquetes perdidos en el flujo == BAJA"""
df_normal.Loss.unique()

array([ 0,  1,  2,  3,  5,  7,  6,  4, 16, 13, 17, 14,  8,  9, 10, 21, 12,
       11], dtype=int64)

In [72]:
""" total de paquetes perdidos en el flujo por el host origen== BAJA"""
df_normal.SrcLoss.unique()

array([ 0,  3,  1, 17, 14,  2,  4,  6,  5], dtype=int64)

In [73]:
""" total de paquetes perdidos en el flujo por el host destino== BAJA"""
df_normal.DstLoss.unique()

array([ 0,  1,  2,  3,  5,  7,  6,  4, 16, 13,  8,  9, 21, 12, 10],
      dtype=int64)

In [ ]:
""" porcentaje de paquetes perdidos en el flujo == BAJA"""
df_normal.pLoss.unique()

In [ ]:
""" porcentaje de paquetes perdidos en el flujo por el host origen == BAJA"""
df_normal.pSrcLoss.unique()

In [ ]:
""" porcentaje de paquetes perdidos en el flujo por el host destino == BAJA"""
df_normal.pDstLoss.unique()

In [77]:
"""total de paquetes retransimitidos en el flujo actual == BAJA"""
df_normal.Retrans.unique()

array([0], dtype=int64)

In [78]:
"""total de paquetes retransimitidos en el flujo por el host origen == BAJA"""
df_normal.SrcRetra.unique()

array([0], dtype=int64)

In [79]:
"""total de paquetes retransimitidos en el flujo por el host destino == BAJA"""
df_normal.DstRetra.unique()

array([0], dtype=int64)

In [81]:
"""porcentaje de paquetes retransimitidos en el flujo == BAJA"""
df_normal.pRetran.unique()

array([0.])

In [82]:
"porcentaje de paquetes retransimitidos en el flujo por el host origen == BAJA"""
df_normal.pSrcRetr.unique()

array([0.])

In [83]:
"porcentaje de paquetes retransimitidos en el flujo por el host destino == BAJA"""
df_normal.pDstRetr.unique()

array([0.])

In [84]:
""" bytes de origen que faltan en el flujo === BAJA"""
df_normal.SrcGap.unique()

array([        nan, 0.00000e+00, 5.12000e+02, 1.77000e+02, 1.00000e+00,
       1.79000e+02, 1.60000e+01, 1.07000e+02, 9.60000e+01, 1.60000e+02,
       3.80000e+01, 4.18000e+02, 1.09600e+03, 3.78000e+02, 3.41000e+02,
       8.37100e+03, 8.14000e+02, 2.16000e+02, 3.58000e+02, 1.19231e+05,
       6.55900e+03, 6.51100e+03, 1.09800e+03, 8.46600e+03, 4.83000e+02,
       8.60000e+01, 1.15300e+03, 4.32000e+02, 3.54000e+02, 1.09440e+04,
       2.19000e+02, 2.17000e+02, 6.33000e+02, 1.26900e+03, 4.33000e+02,
       1.09520e+04, 1.15000e+02])

In [85]:
""" bytes del host destino que faltan en el flujo === BAJA"""
df_normal.DstGap.unique()

array([         nan, 0.000000e+00, 1.770000e+02, 1.600000e+01,
       4.000000e+01, 6.016780e+05, 4.620000e+02, 4.890000e+02,
       3.305165e+06, 2.904300e+04, 4.250000e+02, 5.600000e+01,
       1.560000e+04])

In [86]:
""" cantidad de paquetes por segundo == ALTA """
df_normal.Rate.unique()

array([  0.      ,  68.553047,   0.547982, ..., 103.152061,   1.481107,
         8.460504])

In [87]:
""" cantidad de paquetes por segundo emitido por el host Origen == ALTA """
df_normal.SrcRate.unique()

array([ 0.      , 16.856195,  0.234849, ...,  1.48283 , 55.9319  ,
        2.308415])

In [89]:
""" cantidad de paquetes por segundo emitido por el host Destino == ALTA """
df_normal.DstRate.unique()

array([ 0.      , 51.618725,  0.234876, ..., 47.358898,  0.987575,
        5.383957])

In [91]:
"""direccion de la transaccion o de la comunicacion (normal, desconocido, uno o doble sentido) """
df_normal.Dir.unique()

array([nan, '  <?>', '  <->', '   ->', '  who'], dtype=object)

In [92]:
"""tiempo de llegada entre paquetes de origen == MEDIA"""
df_normal.SIntPkt.unique()

array([        nan,   59.325375, 4258.0485  , ...,   18.08132 ,
       2068.164   ,  996.78225 ])

In [93]:
""" Distribución del tiempo de llegada entre paquetes de origen == MEDIA"""
df_normal.SIntDist.unique()

array([nan])

In [94]:
""" Tiempo de llegada de paquetes que permanece activos en el host origen == ALTA """
df_normal.SIntPktAct.unique()

array([     nan, 0.      , 0.616   , ..., 0.262033, 0.537459, 0.370658])

In [95]:
""" Tiempo extendido que se mantiene activo el flujo == ALTA"""
df_normal.SIntActDist.unique()

array([nan])

In [97]:
""" tiempo que permanenece inactiva la comunicacion despues de la llegada de los paquetes == ALTA"""
df_normal.SIntPktIdl.unique()

array([        nan,   59.325375, 4258.0485  , ...,   21.738957,
       2068.164   ,  996.78225 ])

In [100]:
""" atributo desconocido """
df_normal.SIntIdlDist.unique()

array([nan])

In [101]:
"""tiempo de llegada entre paquetes de destino== MEDIA"""
df_normal.DIntPkt.unique()

array([        nan,   20.016316, 4257.5655  , ...,   21.464324,
        689.477   ,  493.23975 ])

In [102]:
""" Distribución del tiempo de llegada de los paquetes destino == MEDIA"""
df_normal.DIntDist.unique()

array([nan])

In [103]:
""" Tiempo de llegada de paquetes que permanece activos en el host destino== ALTA """
df_normal.DIntPktAct.unique()

array([     nan, 0.110966, 0.      , ..., 0.348846, 0.755518, 0.53477 ])

In [104]:
""" Tiempo extendido que se mantiene inactivo el flujo por parte del host destino == ALTA"""
df_normal.DIntActDist.unique()

array([nan])

In [105]:
""" tiempo que permanenece inactiva la comunicacion despues de la llegada de los paquetes hacia el host origen== ALTA"""
df_normal.DIntPktIdl.unique()

array([        nan,   61.990641, 4257.5655  , ...,   32.097887,
       1034.145   ,  789.104625])

In [106]:
""" tiempo que permanenece inactiva la comunicacion despues de la llegada de los paquetes hacia el host origen== ALTA"""
df_normal.DIntPktIdl.unique()

array([        nan,   61.990641, 4257.5655  , ...,   32.097887,
       1034.145   ,  789.104625])

In [18]:
""" atributo desconocido """
df_normal.DIntIdlDist.unique()

array([nan])

In [107]:
""" tiempo de retardo entre el momento en que se transmite una señal y el momento en que se 
recibe a través de una conexión de red del host origen == MEDIA"""
df_normal.SrcJitter.unique()

array([        nan,  735.935938, 4351.5035  , ..., 1103.81325 ,
       1705.392185, 1111.00325 ])

In [108]:
"""variacion activa del retardo del host origen == MEDIA"""
df_normal.SrcJitAct.unique()

array([     nan, 0.      , 0.9655  , ..., 0.93339 , 3.694388, 1.831155])

In [109]:
""" tiempo de retardo entre el momento en que se transmite una señal y el momento en que se 
recibe a través de una conexión de red del host destino == MEDIA"""
df_normal.DstJitter.unique()

array([         nan, 14844.695978,  4351.9485  , ...,  2024.262294,
       36973.666941, 32951.656984])

In [110]:
"""variacion activa del retardo del host destino == MEDIA"""
df_normal.DstJitAct.unique()

array([     nan, 0.283343, 0.265443, ..., 0.031289, 2.725911, 0.046507])

In [111]:
"""estado de la conexion entre origen y destino == ALTA"""
df_normal.State.unique()

array(['STA', 'CON', 'FIN', 'RST', 'STP', 'INT', 'NRS', 'MHR', 'URP',
       'RSP', 'REQ', 'ECO', 'CLO'], dtype=object)

In [112]:
"""etiqueta del trafico == ALTA"""
df_normal.Label.unique()

array(['Normal'], dtype=object)

In [113]:
"""buffer de datos del host origen"""
df_normal.srcUdata.unique()

array([nan])

In [114]:
"""buffer de datos del host destino"""
df_normal.dstUdata.unique()

array([nan])

In [115]:
"""ventana TCP de origen == BAJA"""
df_normal.SrcWin.unique()

array([   nan, 65535., 41418., ...,   249.,   311.,   343.])

In [ ]:
"""ventana TCP de destino == BAJA"""
df_normal.DstWin.unique()

In [119]:
""" VLAN  de origen = BAJA """
df_normal.sVlan.unique()

array([nan])

In [121]:
""" VLAN  de destino  = BAJA"""
df_normal.dVlan.unique()

array([nan])

In [122]:
""" identificador VLAN  de origen  = BAJA """
df_normal.sVid.unique()

array([nan])

In [123]:
""" identificador VLAN  de destino = BAJA """
df_normal.dVid.unique()

array([nan])

In [125]:
""" prioridad VLAN  de origen = BAJA """
df_normal.sVpri.unique()

array([nan])

In [124]:
""" prioridad VLAN  de destino = BAJA """
df_normal.dVpri.unique()

array([nan])

In [126]:
""" hora de inicio para el filtro de temporizador = BAJA"""
df_normal.SRange.unique()

array([nan])

In [127]:
""" hora de finalizacion para el filtro de temporizador = BAJA"""
df_normal.ERange.unique()

array([nan])

In [128]:
""" número de secuencia base TCP de origen = BAJA"""
df_normal.SrcTCPBase.unique()

array([           nan, 3.73649588e+09, 3.03609234e+09, ...,
       2.31782539e+09, 1.48382969e+09, 8.77187359e+08])

In [129]:
""" número de secuencia base TCP de host destino = BAJA"""
df_normal.DstTCPBase.unique()

array([           nan, 3.06614840e+07, 3.90088038e+08, ...,
       1.33997956e+08, 2.70147490e+09, 7.11832780e+07])

In [130]:
"""tiempo de ida y vuelta en la conexion TCP == ALTA"""
df_normal.TcpRtt.unique()

array([0.      , 0.152041, 0.016229, ..., 0.025128, 0.020968, 0.014697])

In [131]:
"""tiempo de sincronizacion cuando se crea la conexion == ALTA"""
df_normal.SynAck.unique()

array([0.      , 0.152015, 0.01619 , ..., 0.022171, 0.020935, 0.014651])

In [ ]:
""" tiempo entre SYN_ACK y ACK == ?"""
df_normal.AckDat.unique()

In [133]:
""" indicadores de estado de las operaciones que se ejecutan en TCP == MEDIA"""
df_normal.TcpOpt.unique()

array([nan, 'Mws   T', '      T', 'M', '   S  T', 'MwsS  T'], dtype=object)

In [134]:
"""nodo intermedio entre origen y destino"""
df_normal.Inode.unique()

array([nan, '192.168.20.133'], dtype=object)

In [135]:
""" Desplazamiento de bytes del registro en el archivo o flujo. == ?"""
df_normal.Offset.unique()

array([    0,   128,   468, ..., 31852, 32212, 32532], dtype=int64)

In [136]:
"""Promedio del tamanio del paquete emitido por el host origen ==ALTA"""
df_normal.sMeanPktSz.unique()

array([  0.      ,  66.773193,  54.      , ..., 239.733047, 309.350342,
       294.144135])

In [137]:
"""Promedio del tamanio del paquete emitido por el host destino ==ALTA"""
df_normal.dMeanPktSz.unique()

array([   0.      , 3328.307373,   60.      , ...,  257.298065,
        336.140167,  324.684479])

In [138]:
""" Distribucion del tamanio del paquete origen == ALTA"""
df_normal.sPktSz.unique()

array([nan])

In [139]:
""" tamaño máximo del paquete del origen == ALTA"""
df_normal.sMaxPktSz.unique()

array([  nan, 1348.,   54., ..., 1267., 2077., 6994.])

In [140]:
""" Distribucion del tamanio del paquete destino == ALTA"""
df_normal.dPktSz.unique()

array([nan])

In [141]:
""" tamaño máximo del paquete del destino == ALTA"""
df_normal.dMaxPktSz.unique()

array([   nan, 45927.,    60., ...,  1857., 54703.,  3637.])

In [143]:
""" tamaño minimo del paquete del origen == ALTA"""
df_normal.sMinPktSz.unique()

array([  nan,   54.,   75.,   92.,  100.,   97.,   77.,   95.,   84.,
         76.,   74.,   71.,   86.,   87.,   79.,   88.,   72.,   69.,
         80.,   82.,   81.,   78.,   73.,   85.,   89.,   93.,   91.,
         90.,   96.,   66.,   60.,  215.,   70.,   64.,   94.,  139.,
        220.,  137.,   42.,  579.,  216.,   83.,   98.,  250.,  242.,
        243.,  103.,  107.,  102.,  266.,  175.,  151.,  153.,  490.,
        530.,  257.,  249.,  359.,  351.,  179.,  125.,  540.,  183.,
        203.,  113.,   62.,   67.,   99.,  174.,  146.,  188.,  176.,
         65.,  132., 1514.,  306.,  213.,  551.,  381.,  483.,  548.,
        101., 1048.,  301.,  324.])

In [ ]:
""" tamaño minimo del paquete del destino == ALTA"""
df_normal.dMinPktSz.unique()

# 2. Limpieza
Eliminacion de datos faltantes, innecesarios o redundantes.

In [3]:
""" eliminar de atributos innecesarios o que contienen datos faltantes en db normal"""
df_normal.drop(columns=['SrcId','Rank','Trans','SrcMac','DstMac','SrcOui','DstOui','SrcAddr','DstAddr',
'sDSb','dDSb','sCo','dCo','sHops','dHops','sIpId','dIpId','sMpls','dMpls','AutoId','sAS','dAS','iAS','NStrok','sNStrok',
'dNStrok','Loss','SrcLoss','DstLoss','pLoss','pSrcLoss','pDstLoss','Retrans','SrcRetra','DstRetra','pRetran','pSrcRetr','pDstRetr',
'SrcGap','DstGap','SIntDist','SIntActDist','SIntIdlDist','DIntDist','DIntActDist','DIntIdlDist','srcUdata','dstUdata','sVlan','dVlan','sVid',
'dVid','sVpri','dVpri','SRange','ERange','Inode','sPktSz','dPktSz'], axis=1, inplace=True)

In [4]:
""" eliminar de atributos innecesarios o que contienen datos faltantes en db DoS"""
df_dos.drop(columns=['SrcId','Rank','Trans','SrcMac','DstMac','SrcOui','DstOui','SrcAddr','DstAddr',
'sDSb','dDSb','sCo','dCo','sHops','dHops','sIpId','dIpId','sMpls','dMpls','AutoId','sAS','dAS','iAS','NStrok','sNStrok',
'dNStrok','Loss','SrcLoss','DstLoss','pLoss','pSrcLoss','pDstLoss','Retrans','SrcRetra','DstRetra','pRetran','pSrcRetr','pDstRetr',
'SrcGap','DstGap','SIntDist','SIntActDist','SIntIdlDist','DIntDist','DIntActDist','DIntIdlDist','srcUdata','dstUdata','sVlan','dVlan','sVid',
'dVid','sVpri','dVpri','SRange','ERange','Inode','sPktSz','dPktSz'], axis=1, inplace=True)

In [5]:
""" eliminar de atributos innecesarios o que contienen datos faltantes en db Probe"""
df_probe.drop(columns=['SrcId','Rank','Trans','SrcMac','DstMac','SrcOui','DstOui','SrcAddr','DstAddr',
'sDSb','dDSb','sCo','dCo','sHops','dHops','sIpId','dIpId','sMpls','dMpls','AutoId','sAS','dAS','iAS','NStrok','sNStrok',
'dNStrok','Loss','SrcLoss','DstLoss','pLoss','pSrcLoss','pDstLoss','Retrans','SrcRetra','DstRetra','pRetran','pSrcRetr','pDstRetr',
'SrcGap','DstGap','SIntDist','SIntActDist','SIntIdlDist','DIntDist','DIntActDist','DIntIdlDist','srcUdata','dstUdata','sVlan','dVlan','sVid',
'dVid','sVpri','dVpri','SRange','ERange','Inode','sPktSz','dPktSz'], axis=1, inplace=True)

### Valores duplicados

In [6]:
#total de datos duplicados en db normal
df_normal.duplicated().sum()

10016

In [7]:
#total de datos duplicados en db dos
df_dos.duplicated().sum()

0

In [8]:
#total de datos duplicados en db probe
df_probe.duplicated().sum()

0

In [7]:
#filas duplicadas en db normal
df_normal[df_normal.duplicated()]

StartTime         LastTime        Flgs  Seq        Dur  \
11430  21:34:33.203919  21:34:33.203481                0   0.000438   
11431  08:50:25.128119  08:50:35.369085   M            1  10.240966   
11432  08:50:25.383832  08:50:35.630002   M            2  10.246170   
11433  08:50:25.840365  08:50:38.240736   e            3  12.400371   
11434  08:50:25.840499  08:50:38.240766   e            4  12.400267   
...                ...              ...         ...  ...        ...   
21441  09:42:50.444184  09:43:04.753334   e            3  14.309150   
21442  09:42:58.887197  09:43:11.241559   e            2  12.354362   
21443  09:43:02.247270  09:43:11.124772   e            1   8.877502   
21444  09:43:05.940115  09:43:11.040640   e            3   5.100525   
21445  21:34:45.701950  21:34:44.681650                0   1.020300   

         RunTime      IdleTime       Mean  StdDev        Sum  ...  SynAck  \
11430        NaN           NaN        NaN     NaN        NaN  ...     0.0   
11431  10.240966  1.672713e+09  10.240966     0.0  10.240966  ...     0.0   
11432  10.246170  1.672713e+09  10.246170     0.0  10.246170  ...     0.0   
11433  12.400371  1.672713e+09  12.400371     0.0  12.400371  ...     0.0   
11434  12.400267  1.672713e+09  12.400267     0.0  12.400267  ...     0.0   
...          ...           ...        ...     ...        ...  ...     ...   
21441  14.309150  1.672713e+09  14.309150     0.0  14.309150  ...     0.0   
21442  12.354362  1.672713e+09  12.354362     0.0  12.354362  ...     0.0   
21443   8.877502  1.672713e+09   8.877502     0.0   8.877502  ...     0.0   
21444   5.100525  1.672713e+09   5.100525     0.0   5.100525  ...     0.0   
21445        NaN           NaN        NaN     NaN        NaN  ...     0.0   

       AckDat   TcpOpt  Offset   sMeanPktSz  dMeanPktSz  sMaxPktSz  dMaxPktSz  \
11430     0.0      NaN       0     0.000000    0.000000        NaN        NaN   
11431     0.0      NaN     128    54.000000   60.000000       54.0       60.0   
11432     0.0      NaN     428    54.000000   60.000000       54.0       60.0   
11433     0.0      NaN     728   139.000000    0.000000      139.0        NaN   
11434     0.0      NaN     864   139.000000    0.000000      139.0        NaN   
...       ...      ...     ...          ...         ...        ...        ...   
21441     0.0     S  T  226252  1196.666626  123.526314     6178.0      243.0   
21442     0.0     S  T  226580   935.333313  120.933334     6178.0      243.0   
21443     0.0     S  T  226908   407.061523  251.208328     6178.0     1620.0   
21444     0.0     S  T  227256   916.000000  123.866669     6178.0      243.0   
21445     0.0      NaN  227256     0.000000    0.000000        NaN        NaN   

       sMinPktSz dMinPktSz  
11430        NaN       NaN  
11431       54.0      60.0  
11432       54.0      60.0  
11433      139.0       NaN  
11434      139.0       NaN  
...          ...       ...  
21441       66.0      66.0  
21442       66.0      66.0  
21443       66.0      66.0  
21444       66.0      66.0  
21445        NaN       NaN  

[10016 rows x 64 columns]

In [8]:
""" listar caracteristicas """
caracteristicas = ['StartTime','LastTime','Flgs','Seq','Dur','RunTime','IdleTime',
'Mean','StdDev','Sum','Min','Max','Proto','Sport','Dport','sTos','dTos','sTtl','dTtl',
'Cause','TotPkts','SrcPkts','DstPkts','TotBytes','SrcBytes','DstBytes','TotAppByte',
'SAppBytes','DAppBytes','PCRatio','Load','SrcLoad','DstLoad','Rate','SrcRate','DstRate','Dir',
'SIntPkt','SIntPktAct','SIntPktIdl','DIntPkt','DIntPktAct','DIntPktIdl','SrcJitter','SrcJitAct',
'DstJitter','DstJitAct','State','Label','SrcWin','DstWin','SrcTCPBase','DstTCPBase',
'TcpRtt','SynAck','AckDat','TcpOpt','Offset','sMeanPktSz','dMeanPktSz','sMaxPktSz','dMaxPktSz',
'sMinPktSz','dMinPktSz']

In [12]:
""" funcion para obtener cantidad de datos duplicados por cada atributo"""
def encontrar_duplicados(n_caracteristicas):
    for i in n_caracteristicas:
        """mostrar columna y suma de valores duplicados"""
        print(i,':' ,df_normal.duplicated(i,keep=False).sum())

In [13]:
encontrar_duplicados(caracteristicas)

StartTime : 20186
LastTime : 20236
Flgs : 101063
Seq : 96946
Dur : 70079
RunTime : 70111
IdleTime : 101066
Mean : 70111
StdDev : 101066
Sum : 70111
Min : 70111
Max : 70111
Proto : 101066
Sport : 99203
Dport : 100992
sTos : 101001
dTos : 101066
sTtl : 101066
dTtl : 101066
Cause : 101066
TotPkts : 100395
SrcPkts : 100646
DstPkts : 100589
TotBytes : 92355
SrcBytes : 96321
DstBytes : 94577
TotAppByte : 93714
SAppBytes : 97125
DAppBytes : 95665
PCRatio : 90415
Load : 72288
SrcLoad : 73464
DstLoad : 74685
Rate : 69932
SrcRate : 75961
DstRate : 77211
Dir : 101066
SIntPkt : 72768
SIntPktAct : 96673
SIntPktIdl : 74031
DIntPkt : 74303
DIntPktAct : 94477
DIntPktIdl : 74318
SrcJitter : 75160
SrcJitAct : 96206
DstJitter : 75328
DstJitAct : 95132
State : 101066
Label : 101066
SrcWin : 100522
DstWin : 101016
SrcTCPBase : 76000
DstTCPBase : 75733
TcpRtt : 97749
SynAck : 97760
AckDat : 100970
TcpOpt : 101066
Offset : 28400
sMeanPktSz : 93611
dMeanPktSz : 92715
sMaxPktSz : 100346
dMaxPktSz : 99626
sMinP

In [10]:
df_normal = df_normal.drop_duplicates(subset=caracteristicas[2:65],keep="last")

### Analizar nomenclaturas

In [14]:
df_normal.Flgs.unique()

array(['          ', ' M        ', ' e        ', ' M g      ',
       ' M r      ', ' M dS     ', ' e g      ', ' e     A  ',
       ' eU       ', ' M d      ', ' e s      ', ' M s      ',
       ' e d      ', ' M  S     ', ' M i      ', ' M  D     ',
       ' M sD     ', ' M &      ', ' e *      ', ' M *      ',
       ' e dD     '], dtype=object)